name: Test Cache download failure
on:
  workflow_dispatch:
jobs:
  test:
    name: golang
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Get GO cache directory path
      id: go-cache-dir-path
      run: echo "::set-output name=dir::$(go env GOCACHE)"
      shell: bash
